# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
